# 
# Do not Edit! Generated by:
# spectacle version 0.13
# 
# >> macros
# << macros

Name:       meego-rpm-config
Summary:    MeeGo specific rpm configuration files
Version:    0.3
Release:    1
Group:      Development/System
License:    GPL+
BuildArch:  noarch
URL:        http://meego.com
Source0:    meego-rpm-config-%{version}.tar.bz2
Source100:  meego-rpm-config.yaml
Provides:   moblin-rpm-config
Obsoletes:   moblin-rpm-config =< 2.1.92-3.8

%description
MeeGo specific rpm configuration files.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make DESTDIR=${RPM_BUILD_ROOT} install


# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_prefix}/lib/rpm/meego
# << files


