# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       meego-rpm-config

# >> macros
# << macros
%define disable_docs_package 1

Summary:    MeeGo specific rpm configuration files
Version:    0.18
Release:    1
Group:      Development/System
License:    GPL+
BuildArch:  noarch
URL:        http://meego.com
Source0:    meego-rpm-config-%{version}.tar.bz2
Patch0:     meego-rpm-config-0.18-merchanges.patch

%description
MeeGo specific rpm configuration files.

%prep
%setup -q -n %{name}-%{version}

# meego-rpm-config-0.18-merchanges.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make DESTDIR=${RPM_BUILD_ROOT} install
# << install post

%files
%defattr(-,root,root,-)
# >> files
%{_prefix}/lib/rpm/meego
# << files
